name: 'Polymarket Local'
values:
  - key: baseUrl
    value: 'https://gamma-api.polymarket.com'
    enabled: true
    type: default
  - key: clobBaseUrl
    value: 'https://clob.polymarket.com'
    enabled: true
    type: default
  - key: tokenId
    value: ''
    enabled: true
    type: default
  - key: category
    value: 'politics'
    enabled: true
    type: default
